runningMass = rhod.*Ad;
lambda = 22.896171148120008;
E = 1.5264e09;
G = 5.616e8;
spanCoord = xd*cosd(lambda);
EIyy = Iyyd*E;
EIzz = Izzd*E;
GJ = Jd*G;
figure;
title('spanwise stiffness');
hold on;
%plot(xd, Ixxd, '*c');
plot(xd, Iyyd, '*b');
plot(xd, Izzd, '*r');
plot(xd, Jd, '*k');
figure;
hold on;
title('spanwise running mas');
plot(xd, runningMass, '*k');